receivers:
    opencensus:
        endpoint: 0.0.0.0:55678
    otlp:
        endpoint: 0.0.0.0:55680
exporters:
    logging:
        loglevel: debug
processors:
    batch:
    queued_retry:
service:
    pipelines:
        traces:
            receivers: [otlp, opencensus]
            exporters: [logging]
            processors: [batch, queued_retry]
        metrics:
            receivers: [otlp, opencensus]
            exporters: [logging]